version: "3"
services:
  shop-product-api:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app/
      - /app/node_modules/
    environment:
      - NODE_ENV=development
    command: npm run watch
