apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-api-product-service
  labels:
    app: shop-api-product-service
spec:
  selector:
    matchLabels:
      app: shop-api-product-service
  replicas: 2
  template:
    metadata:
      labels:
        app: shop-api-product-service
    spec:
      containers:
        - name: shop-api-product-service
          imagePullPolicy: Always
          image: thusharathiwanka/shop-api-product-service
          ports:
            - containerPort: 5001
