apiVersion: v1
kind: Service
metadata:
  name: shop-api-product-service
  labels:
    app: shop-api-product-service
spec:
  selector:
    app: shop-api-product-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
