name: Dockerize product service

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build docker container image and publish to dockerhub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Publish to dockerhub
      uses: docker/build-push-action@v3
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: thusharathiwanka/product-service
